### ISSUE TITLE
HTTP2 & TLS?

### ISSUE THREAD

**Issue by kkocdko** [kkocdko/ksite#1]
* [x] IP cert from [ZeroSSL](https://zerossl.com).
* [x] TLS + HTTP 1.1.
* [x] HTTP 2 and TLS.
* [x] Redirect HTTP to HTTPS.
* [x] Load cert and key from database.
* [x] TLS handshake timeout.
* [x] Avoid using hyper's `Accept` trait, fix TLS handshake blocking bug.
* [x] WebSocket over TLS.
* [x] Use tlsimple.
* [x] Benchmark on Linux.
* [x] Fit hyper 1.0 in the future.
* [ ] Certificate auto resign?
* [x] 🚀 Deploy!

**Comment by kkocdko** [comment]
degenerate: after switch to native-tls, the `http2 + tls` not longer works.

> Fixed.

**Comment by kkocdko** [comment]
Deployed!

**Comment by kkocdko** [comment]
After `tls_next`, WebSocket was broken.

```
thread 'tokio-runtime-worker' panicked at 'connection upgrade failed: hyper::Error(User(ManualUpgrade))', /home/kkocdko/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/axum-0.5.15/src/extract/ws.rs:244:45
stack backtrace:
   0:     0x5648707d0fdd - std::backtrace_rs::backtrace::libunwind::trace::h3c69d31d7b3da294
                               at /rustc/1f34da9ec8a85b6f86c5fa1c121ab6f88f2f4966/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
...
```

> Fixed.

**Comment by kkocdko** [comment]
WebSocket removed in [a756d64](https://github.com/kkocdko/ksite/commit/a756d64).

**Comment by kkocdko** [comment]
Benchmark with TLS enabled always failed on linux (but it's normal on windows).

Seems a problem of rustls. any idea to fix this?

**Comment by kkocdko** [comment]
Sometimes the cert error msg shown on browser, why?

**Comment by kkocdko** [comment]
The `tower` was removed from direct dependency after https://github.com/kkocdko/ksite/commit/256af065f7f91ccf3f7bf14e58a8fe2189ff7b32 .
